### ISSUE TITLE
OCISchema Version option

### ISSUE THREAD

**Issue by TwinMist** [cwmiller/broadworks-connector#31]
Hi
Could there be a option for what schema version is download and used
since downloading V3 there is no UserModifyRequest17sp4 which seams strange.
we are running R20
goes from  
UserModifyRequest14
UserModifyRequest16
UserModifyRequest21
UserModifyRequest22

thanks

**Comment by cwmiller** [comment]
I noticed some strange things like that too. I had to make several modifications to the XSD files from BroadSoft to process them because they contained a few errors. I'm guessing the removal of `UserModifyRequest17sp4` was also a mistake they made since other requests from 17sp4 are still in there such as `UserGetRequest17sp4`.

I'm going to compare the previous version of XSD files with the current and restore these types that got removed.

**Comment by TwinMist** [comment]
Thanks, Looks forward to the next release.

**Comment by TwinMist** [comment]
Any update on this?
many thanks

**Comment by cwmiller** [comment]
Version 3.0.2 has been released with the restored types.
