### ISSUE TITLE
Single NameSpace

### ISSUE THREAD

**Issue by andyrav** [cwmiller/broadworks-connector#5]
Hi 
It is possible to combine the request and responcse namespace into a single entity?
use CWM\BroadWorksConnector\Ocip\Models\UserGetListInGroupRequest;
use CWM\BroadWorksConnector\Ocip\Models\UserGetListInGroupResponse;
becomes
use CWM\BroadWorksConnector\Ocip\Models\UserGetListInGroup
or
use CWM\BroadWorksConnector\Ocip\Models\UserGetListInGroupRequest;

great work...

**Comment by cwmiller** [comment]
Not really since each class needs to be in its own file.

If you'd like to reduce the number of `use`s at the top of your script, you could always just do `use CWM\BroadWorksConnector\Ocip\Models;`

The only drawback to this is you'd always have to reference Models e.g. `$request = new Models\UserGetListInGroupRequest()`. Or you can use an alias by doing  `use CWM\BroadWorksConnector\Ocip\Models as M;` then referencing the classes as `M\UserGetListInGroupRequest`, etc.

**Comment by andyrav** [comment]
Could you create something that loads all the classes ? or is this to much overhead?

Great work on this tool.
